// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "WEdy!xpNa}i*SDpgE%1#":
            case "MYSPRITE":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f 8 8 8 8 f 7 f . . . . 
. . f f 8 8 8 8 f 7 7 7 f . . . 
. . f 8 8 8 f f 8 8 8 8 f . . . 
. . f f f f 8 8 7 7 7 7 8 f . . 
. . f 8 7 7 7 f f f f 8 7 f . . 
. f f f f f f f 8 8 8 f f f . . 
. f f 8 6 6 8 b f 6 6 8 8 f . . 
. f 8 8 6 d 6 1 f d d 8 f . . . 
. . f 8 8 8 8 8 d d d f . . . . 
. . . . f 6 d d 8 6 8 f . . . . 
. . . . f 8 d d 8 7 7 f . . . . 
. . . f f f 8 8 f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`;
            case "image1":
            case "purpdino":return img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c a a a a c c . . . . . . 
. c a a a a a a a a c . . . . . 
c a a a a a 1 f a a a c . . . . 
c a a a a a f f a a a a c . . . 
c a a a a a a a a a a a c . . . 
c c b b 1 b a a a a a a 8 c . . 
c a 3 3 3 a a a a a 8 8 8 c . . 
. a a a a a a a a a 8 8 8 c . . 
. . c a a c a a b 8 8 8 8 c . . 
. c a a c a a b b 8 8 8 8 c c c 
. c c c c c c 8 8 8 8 8 8 8 8 c 
. . . c c c c 8 a a b 8 8 c c . 
. . c a a c c c a a b c c . . . 
. . c c c c c 8 a a c . . . . . 
`;
            case "image2":
            case "yellowdino":return img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c 5 5 5 5 c c . . . . . . 
. c 5 5 5 5 5 5 5 5 c . . . . . 
c 5 5 5 5 5 1 f 5 5 5 c . . . . 
c 5 5 5 5 5 f f 5 5 5 5 c . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. b 5 5 5 5 5 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c c 
. c c c c c c d d d d d d d d c 
. . . c c c c d 5 5 b d d c c . 
. . c b b c c c 5 5 b c c . . . 
. . c c c c c d 5 5 c . . . . . 
`;
            case "image3":
            case "hitbox":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . d d . . . . . 
. . . . . . . d d d d . . . . . 
. . . . . . d . . . d . . . . . 
. . . . . d . . . . d . . . . . 
. . . . d d . . . . d . . . . . 
. . . . . d d . . . d . . . . . 
. . . . . . d . . . d . . . . . 
. . . . . . d d d . d . . . . . 
. . . . . . . . d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "princess":return img`
. . . f 4 4 f f f f . . . . . . 
. . f 4 5 5 4 5 f b f f . . . . 
. . f 5 5 5 5 4 e 3 3 b f . . . 
. . f e 4 4 4 e 3 3 3 3 b f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. f 3 3 e e 3 b e 3 3 3 3 f . . 
. f 3 3 e e e f f 3 3 3 3 f . . 
. f 3 e e e f b f b b b b f . . 
. . f e 4 4 f 1 e b b b b f . . 
. . . f 4 4 4 4 f b b b b f f . 
. . . f e e e f f f b b b b f . 
. . . f d d d e 4 4 f b b f . . 
. . . f d d d e 4 4 e f f . . . 
. . f b d b d b e e b f . . . . 
. . f f 1 d 1 d 1 d f f . . . . 
. . . . f f b b f f . . . . . . 
`;
            case "image5":
            case "mayor":return img`
. . 1 1 1 1 1 1 1 . . . 
. . 1 1 1 1 1 1 1 . . . 
. 1 1 1 1 1 1 1 1 1 . . 
. 1 1 1 1 1 1 1 1 1 . . 
1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 
f f f f f f f f f f f f 
. f c 1 1 f f 1 c 1 f f 
. . f d d d d 1 d 1 f . 
. . f b b d c c f f f . 
. . f c 1 c d d 1 f . . 
. . f 1 1 c d d c f . . 
. f f 6 6 f c c f f f . 
. f f f f f f f f f f . 
. . f f f . . . f f . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "swipe":
            case "anim1":return [img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe44ebf44ecddc.........
fee4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
